### PR TITLE
Changing the Factory page based on Arran's suggestions over Discord

### PR DESCRIPTION
**Pull request by Zebax9**
Factory page is now displaying factory log data, and not its initial redundant parameters such as status, assigned PO, and location (which are all also displayed on the machines page).

The page still has the colour indicator for the machine status. The 7 quantitative fields from the Log data for each machine are displayed as they are in their current state (a.k.a. at the end of the csv). I have tried to order them with what a manager, or even the POs, would care for the most towards the top, with possible fields that could act as warning signs toward the bottom.

However, some of my code is cheating a little bit as I am getting quite confused about how similar functions have been implemented on the other pages. My SQL query for fetching the Log data is manually writing in the most up-to-date timestamp, instead of finding that out properly. I am also manually associating the names of the machines with their machineID, as I keep trying to implement the same getMachineName() function from the Reports page, but it keeps breaking and I'm not entirely sure where I am going wrong there. I also still haven't properly implemented the buttons at the bottom. I'd like to use the same date input from the Reports page as well, but I am getting very lost looking into that page. The +/- 30min buttons should also be implemented by adjusting the SQL query?

Apologies for not entirely finishing this page before the pull request, but I think I do need some help with the final pieces. I normally would like to bog down for a week and really research this properly, but especially with the presentation due so soon, I am hoping a little help from you guys could speed me up quite a lot.

Let me know if there are any styling issues with the spacing, last time seemed to be a bit sensitive and did not look the same as on my screen. There should be 3 columns.

### CODE REVIEW

**Comment by JoelBts** [comment]
I may be misunderstanding what you are trying to do, but you want to get the most recent (or matching some timestamp?) log entry for each machine and also the machine name, right? Retrieving the corresponding machine name for a machineID in Log can be done in SQL with a join, and to find the most recent timestamp you can use MAX() which gives the 'highest' timestamp. So something like:

```
SELECT l.*, m.name AS machineName
FROM log l
INNER JOIN (
    SELECT machineID, MAX(timestamp) as mostRecentTimestamp
    FROM log
    GROUP BY machineID
) r ON l.machineID = r.machineID AND l.timestamp = r.mostRecentTimestamp
INNER JOIN Machine m ON l.machineID = m.machineID;
```
I know that looks a bit complicated, but basically the first join gets only the log entry for each machine with the most recent (MAX()) timestamp. The second join gets the machine name from the machine table which corresponds to the machineID in the log table, and so you end up with an extra field machineName that you can use instead of having to use the switch case which would break if another machine was added to the database. 

If you wanted to get the most recent log for each machine from some timestamp for example for the +/-30mins function you could adjust the sql slightly:
```
$sql  = "SELECT l.*, m.name AS machineName
FROM log l
INNER JOIN (
    SELECT machineID, MAX(timestamp) as closestRecentTimestamp
    FROM log
    WHERE timestamp <= ?
    GROUP BY machineID
) r ON l.machineID = r.machineID AND l.timestamp = r.closestRecentTimestamp
INNER JOIN Machine m ON l.machineID = m.machineID;"
```
This will get the log entries for the most recent timestamp that is in the log table to the timestamp that you give it.

**Comment by Zebax9** [comment]
Amazing, thank you for making that query for me, much appreciated! Kept thinking about functions I'd have to make and didn't think of a table join.

I am still thinking of how to properly implement the +/-30min function, and then also implementing a similar date select function like from Reports. I can try to give it another crack tomorrow night after my 8-5 shift, but I'm not honestly sure how I should start (I'd be maybe changing the SQL query with a DATEADD() method and then rebuilding the list with each click?). 

Overall, are you guys happy with this page layout?

**Comment by ArranWill** [comment]
Excellent progress Brad. An alternate to using DATEADD() is doing it in PHP with date_modify()
`$current_time = new DateTime('2024-07-01 23:30');
$new_time = date_modify($current_time, '+30 minutes');`
I don't know what will be easiest for you.

The styling is coming on really well. Here are some comments:
* You can use white-space: nowrap; on the machine-table td to force the table data to one line.
* I'd change listSmall width to 64% to match the other pages.
* You're using id list-boxes for all list items, I think you mean to use a class. I'd change the width such that there are two list items per row. You might need to set the margin for the first but not the second to avoid extra margin on the right column.

**Comment by JoelBts** [comment]
Another option for handling the time would be to use GET, and all the changing and stuff could be done in javascript, which might be simpler to implement with dynamically changing the time you are displaying logs for. 

So at the top of the factory.php page somewhere you would have something like:
```
        date_default_timezone_set('Australia/Adelaide');
        // Uses GET to set the disply time. Defaults to the current time. This is should be in the expected SQL format
        $currentDisplayTimestamp = htmlspecialchars(isset($_GET['timestamp']) ? $_GET['timestamp'] : date('Y-m-d H:i:s'));
        // Reformats to the format required for the datetime input i'll mention in a minute
        $currentDisplayDateTimeLocal = date('Y-m-d\TH:i', strtotime($currentDisplayTimestamp));
```

You would then continue with the sql query, using the $currentDisplayTimestamp to only get the most recent log entry:
```
        // SQL query gets most recent log entry for each machine from supplied timestamp
            $sql = "SELECT l.*, m.name AS machineName
                    FROM log l
                    INNER JOIN (
                        SELECT machineID, MAX(timestamp) as mostRecentTimestamp
                        FROM log
                        WHERE timestamp <= ?
                        GROUP BY machineID
                    ) r ON l.machineID = r.machineID AND l.timestamp = r.mostRecentTimestamp
                    INNER JOIN Machine m ON l.machineID = m.machineID;"; 
            $stmt = mysqli_prepare($conn, $sql);
            mysqli_stmt_bind_param($stmt, "s", $currentDisplayTimestamp);
            mysqli_stmt_execute($stmt);
            $result = mysqli_stmt_get_result($stmt);
```

You can probably just have buttons with onclick for the +/- 30 mins, and an input type="datetime-local" for the time with onchange, something like:
```
<input class="machines-button" id="datetime-inp" type="datetime-local" value="$currentDisplayDateTimeLocal" onchange="setTimestamp()">
```
And use value= to fill it in with the timestamp GET filed from before, which by default should be the current time.

Then in js you would be able to access the current value, and by setting timestamp=xxx in the address bar it will update the sql query to display the logs from the selected time:
```
function setTimestamp() {
    // Gets the current timestamp from the input
    const timestamp = document.getElementById('datetime-inp').value;
    const QUERY_STRING = window.location.search;
    const QUERY_PARAMETERS = new URLSearchParams(QUERY_STRING);
    // adds the timestamp to the address bar
    window.location.href = `?timestamp=${timestamp}&machineID=${QUERY_PARAMETERS.get("machineID")}`;
}
```

It may also be worth copying Arran's function from reports to make the whole think clickable to select the datetime with a click event listener. You would need to wrap the datetime input in a div, which may mess up the styling, i'm not sure.
```
document.addEventListener('DOMContentLoaded', () => {
    const datetimeInput = document.getElementById('datetime-inp');
    const datetimeWrapper = document.getElementById('datetime-inp-wrapper');
    datetimeWrapper.addEventListener('click', () => {
    datetimeInput.showPicker();
    });
});
```

And finally for the +/- 30 mins, it should be fairly straightforward to change (after a bit of testing it turns out it was not as straightforward as I thought, you have to convert it to a Date object and then rebuild it into the correct format since I couldn't find an existin method that worked properly). Its probably also important to check that the time isn't being set to the future (> curreent time). But something like this should work for + 30 mins:
```
// Gets the current timestamp from the input
        const timestamp = document.getElementById('datetime-inp').value;
        // Convert to a Date object to access the methods
        let timestampDate = new Date(timestamp);
        // Stops setting time to the future (> current time)
        if(timestampDate.getTime() + (30* 60 * 1000) <= Date.now()) {
        // Adds (or subtracts) 30 minutes (in milliseconds) to the timestamp
        let newTime = new Date(timestampDate.setTime(timestampDate.getTime() + (30* 60 * 1000)));
        // Reformats the time back into the required format
        const newFormattedTime = newTime.getFullYear() + "-" + (newTime.getMonth() + 1).toString().padStart(2, 0) + "-" + newTime.getDate().toString().padStart(2, 0) + "T" + 
        newTime.getHours().toString().padStart(2, 0) + ":" + newTime.getMinutes().toString().padStart(2, 0);
        //Updates the input with the new time
        document.getElementById('datetime-inp').value = newFormattedTime;
        // adds the new timestamp to the address bar
        const QUERY_STRING = window.location.search;
        const QUERY_PARAMETERS = new URLSearchParams(QUERY_STRING);
        window.location.href = `?timestamp=${newFormattedTime}&machineID=${QUERY_PARAMETERS.get("machineID")}`;
```

And then for - 30 mins you just change the + to a -, or you could make one function to handle both.

Hopefully that makes sense, and gives you an idea of how you might get it working.

**Comment by Zebax9** [comment]
Styling changes were fine. Made more consistent with other pages. Let me know if the stying looks good on your ends

Still honestly very stumped with the time buttons at the bottom, even after all of your guys' amazing help. Feel like I might be running out of time here so I just made sure the styling looked like it worked..

Have also added the missing features section on the report document for this page

**Pull request closed without merging**
